project_id               = "<your-project-id>"
project_number           = "<your-project-number>"
region                   = "<your-region>"
langfuse_version         = 3
langfuse_worker_version  = 3
nextauth_secret          = "<secret>" # Generate your own value: `openssl rand -base64 32`
salt                     = "<salt>"   # Generate your own value: `openssl rand -base64 32`
encryption_key           = "<key>"    # Generate your own value: `openssl rand -hex 32`
web_repository_id        = "langfuse-web-repo"
worker_repository_id     = "langfuse-worker-repo"
clickhouse_repository_id = "langfuse-clickhouse-repo"
clickhouse_version       = "latest"
bucket_name              = "langfuse"
